-- Migration: Add barcode_value and is_shopify_synced to storefront_aliases for Unified Parity Engine
-- Date: 2026-06-01

ALTER TABLE public.storefront_aliases ADD COLUMN IF NOT EXISTS barcode_value text;
ALTER TABLE public.storefront_aliases ADD COLUMN IF NOT EXISTS is_shopify_synced boolean DEFAULT false;

-- Add a comment to the table columns for clarity
COMMENT ON COLUMN public.storefront_aliases.barcode_value IS 'The physical 9-digit barcode sequence generated by Shopify MS Barcodes app or internal emulator.';
COMMENT ON COLUMN public.storefront_aliases.is_shopify_synced IS 'True if the record was fetched and verified from Shopify storefront; false if generated locally by the warehouse emulator.';
