-- 1. Add new operational columns to sales_ledger
ALTER TABLE sales_ledger
ADD COLUMN IF NOT EXISTS customer_email_hash VARCHAR DEFAULT NULL,
ADD COLUMN IF NOT EXISTS customer_phone_hash VARCHAR DEFAULT NULL,
ADD COLUMN IF NOT EXISTS shipping_name_hash VARCHAR DEFAULT NULL,
ADD COLUMN IF NOT EXISTS shipping_address_hash VARCHAR DEFAULT NULL,
ADD COLUMN IF NOT EXISTS refunded_amount NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS tracking_number VARCHAR DEFAULT NULL,
ADD COLUMN IF NOT EXISTS carrier_name VARCHAR DEFAULT NULL,
ADD COLUMN IF NOT EXISTS actual_shipping_cost NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_payout NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS transaction_type VARCHAR DEFAULT 'Standard';
